[project]
name = "pyLaserPulse"
authors = [{name = "James Feehan", email = "pylaserpulse@outlook.com"}]
dynamic = ["0.0.0", "Simulation toolbox for simulating nonlinear passive and active fibre systems."]
